name: Branch Protection

on:
  push:
    branches:
      - main  # Adjust this according to your default branch

jobs:
  apply_branch_protection:
    runs-on: ubuntu-latest

    steps:
      - name: Check if repository is test-repo
        id: check_repo
        run: echo "::set-output name=is_test_repo::${{ github.repository == 'your_username/test-repo' }}"

      - name: Apply branch protection if repository is test-repo
        if: steps.check_repo.outputs.is_test_repo
        run: |
          curl -X PUT \
          -H "Accept: application/vnd.github.luke-cage-preview+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
          -d '{
                "required_status_checks": null,
                "enforce_admins": true,
                "required_pull_request_reviews": {
                  "dismiss_stale_reviews": true,
                  "require_code_owner_reviews": true,
                  "required_approving_review_count": 1
                },
                "restrictions": null
              }'
